name: MCP Dockmaster Tauri Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/mcp-dockmaster/src-tauri/**'
      - '.github/workflows/mcp-dockmaster-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/mcp-dockmaster/src-tauri/**'
      - '.github/workflows/mcp-dockmaster-tests.yml'
  workflow_dispatch:

jobs:
  test-mcp-dockmaster-tauri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci

      - name: Install Debian Dependencie
        run: |
          sudo apt-get update
          sudo apt-get install libglib2.0-dev libwebkit2gtk-4.1-dev build-essential wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev libasound2-dev
        
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
          
      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            apps/mcp-dockmaster/src-tauri/target
          key: ${{ runner.os }}-cargo-dockmaster-${{ hashFiles('apps/mcp-dockmaster/src-tauri/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-


      - name: Run Tauri tests
        working-directory: apps/mcp-dockmaster/src-tauri
        run: cargo test
          
      - name: Run clippy
        working-directory: apps/mcp-dockmaster/src-tauri
        run: cargo clippy -- -D warnings
